-- PUNTO 1

SELECT P.COD_PC, P.NOME, P.TIPO, P.NOME_PROPRIETARIO
FROM PC AS P, RIPARAZIONE AS R
WHERE P.COD_PC = R.REF_PC;

-- PUNTO 2

SELECT P.COD_PC, P.NOME, P.TIPO, P.NOME_PROPRIETARIO
FROM PC AS P, RIPARAZIONE AS R
WHERE P.COD_PC = R.REF_PC AND R.DATA_RIPARAZIONE >= '01/01/2023' AND R.DATA_RIPARAZIONE <= '31/31/2023';

-- PUNTO 3

SELECT P.COD_PC, P.NOME, P.TIPO, P.NOME_PROPRIETARIO
FROM PC AS P, RIPARAZIONE AS R
WHERE P.COD_PC = R.REF_PC AND R.DATA_RIPARAZIONE >= '01/01/2023' AND R.DATA_RIPARAZIONE <= '31/31/2023'
AND R.REF_T = 'GFFF23';