-- PUNTO 1

SELECT P.COD_PC, P.NOME, P.TIPO, P.NOME_PROPRIETARIO
FROM PC AS P, RIPARAZIONE AS R
WHERE P.COD_PC = R.REF_PC;

-- PUNTO 2

SELECT P.COD_PC, P.NOME, P.TIPO, P.NOME_PROPRIETARIO
FROM PC AS P, RIPARAZIONE AS R
WHERE P.COD_PC = R.REF_PC AND R.DATA_RIPARAZIONE >= '01/01/2023' AND R.DATA_RIPARAZIONE <= '31/31/2023';

-- PUNTO 3

SELECT P.COD_PC, P.NOME, P.TIPO, P.NOME_PROPRIETARIO
FROM PC AS P, RIPARAZIONE AS R
WHERE P.COD_PC = R.REF_PC AND R.DATA_RIPARAZIONE >= '01/01/2023' AND R.DATA_RIPARAZIONE <= '31/31/2023'
AND R.REF_T = 'GFFF23';

-- PUNTO 4 [[stessa data - stesso tecnico]]

SELECT R1.REF_CP, R2.COD_CP
FROM RIPARAZIONE AS R1, RIPARAZIONE AS R2
WHERE R1.REF_CF = R2.REF_CF AND R1.DATA_RIP = R2.DATA_RIP AND R1.REF_CP > R2.REF_CP -- Scartare le identita e le coppie allo specchio

