-- DATI DI PERSONA
SELECT * FROM PERSONA;
-- DATI DI OGGETTO
SELECT * FROM OGGETTO;
-- DATI DI ACQUISTO
SELECT * FROM ACQUISTO
ORDER BY REF_O;

-- [ ESPERIMENTAZIONI ]

SELECT P.NOME AS ACQUISTATORE, O.NOME_O AS OGGETTO_ACQUISTATO
FROM OGGETTO O, ACQUISTO A, PERSONA P
WHERE O.COD_O = A.REF_O AND A.REF_P = P.COD_P
GROUP BY P.NOME, O.NOME_O
ORDER BY P.NOME;

-- [ ESPERIMENTAZIONE 2 ]

SELECT P.NOME AS ACQUISTATORE, O.NOME_O AS OGGETTO_ACQUISTATO
FROM OGGETTO O, ACQUISTO A, PERSONA P
WHERE O.COD_O = A.REF_O AND A.REF_P = P.COD_P
GROUP BY P.NOME, O.NOME_O, O.CATEGORIA
HAVING CATEGORIA = 'Elettronica';

-- [ DIVISIONE ]
/* Selezionare Codice, Nome e Categoria degli oggetti di Accessori che sono stati acquistati da tutte le persone di sesso M nel 2023 in
quantita' maggiore uguale di 2
*/

SELECT O.COD_O, O.NOME_O, O.CATEGORIA
FROM OGGETTO O
WHERE O.CATEGORIA = 'Accessori' AND NOT EXISTS 
	(
	SELECT *
	FROM PERSONA P 
	WHERE P.SESSO = 'M' AND NOT EXISTS 
		(
		SELECT *
        FROM ACQUISTO A 
        WHERE A.DATA_ACQUISTO BETWEEN '2023-01-01' AND '2023-12-31' AND A.QUANTITA >= 2 AND
        A.REF_P = P.COD_P AND A.REF_O = O.COD_O
		)
);
/* SELEZIONO UNA PERSONA PER VOLTA, E VERIFICO CHE NON ESISTA UN OGGETTO CHE QUELLA PERSONA NON ABBIA ACQUISTATO

-- -- -- -- --

LE PERSONE DI SESSO MASCHILE CHE HANNO COMPRATO TUTTI GLI OGGETTI DI ELETTRONICA NEL 2023

*/
SELECT P.COD_P, P.NOME, P.COGNOME
FROM PERSONA P
WHERE P.SESSO = 'M' AND NOT EXISTS (
    SELECT *
    FROM OGGETTO O 
    WHERE O.CATEGORIA = 'ELETTRONICA' AND NOT EXISTS (
        SELECT *
        FROM ACQUISTO A 
        WHERE A.DATA_ACQUISTO >= '2023-01-01' AND 
        A.DATA_ACQUISTO <= '2023-12-31'AND 
        A.REF_P = P.COD_P AND
        A.REF_O = O.COD_O
    )
);

/* DOPPIO GROUP BY

SELEZIONARE LE PERSONE CHE HANNO ACQUISTATO PIU' OGGETTI DI TUTTI
+ MAX GLOBALE E IL MAX LOCALE
Questo e' un problema di massimo globale, indifferentemente dal tipo di oggetti comprati io voglio sapere la persona che ha acquistato piu' oggetti



SELECT P.COD_P, P.NOME, P.COGNOME, COUNT(*) AS NUM_ACQUISTI
FROM PERSONA P, ACQUISTO A
WHERE P.COD_P = A.REF_P
GROUP BY COD_P, NOME, COGNOME
HAVING MAX(COUNT(*)) E' UN ERRORE GRAVE

1. ERRORE DUE OPERATORI DENTRO HAVING
2. NON POSSO USARE GLI OPERATORI AGGREGATI SENZA GLI OPERATORI DI CONFRONTO

*/

SELECT P.COD_P, P.NOME, P.COGNOME, COUNT(*)
FROM PERSONA P, ACQUISTO A
WHERE P.COD_P = A.REF_P
GROUP BY P.COD_P, P.NOME, P.COGNOME
HAVING COUNT(*) >= ALL(
    SELECT COUNT(*)
    FROM PERSONA P, ACQUISTO A1
    WHERE P.COD_P = A1.REF_P
    GROUP BY A1.REF_P
);

-- 1. COSA RESTITUISCE L'INTERROGAZIONE PIU' INTERNA = IL NUMERO DI ACQUISTI PER OGNI PERSONA (REF_P)
-- 2. TRUCCO = USO 3 OPERATORI CON DUE INTERROGAZIONI
-- 3. =MAX E' UN GRAVE ERRORE LOGICO, QUINDI FACCIO >=
-- 4. >= FUNZIONA COME MAX MA MI CONSENTE DI BYPASSARE IL PROBLEMA CHE POSSO UTILIZZARE SOLO UN OPERATORE AGGREGATO PER CIASCUNA QUERY

-- MASSIMO LOCALE: VOGLIO SAPERE PER OGNI OGGETTO LE PERSONE CHE HANNO FATTO PIU ACQUISTI DI QUELL'OGGETTO
-- IO DEVO CONFRONTARE PER OGNI OGGETTO GLI ACQUISTI CHE TUTTE LE PERSONE HANNO FATTO DI SOLO QUELL'OGGETTO
-- DEVO PER FORZA USARE IL PASSAGGIO DI PARAMETRI
-- V1

SELECT A1.REF_P, A1.REF_O, COUNT(*)
FROM ACQUISTO A1
GROUP BY A1.REF_P, A1.REF_O
HAVING COUNT(*) >= ALL (SELECT COUNT(*)
						FROM ACQUISTO A2
						WHERE A2.REF_O = A1.REF_O
                        GROUP BY REF_P)
ORDER BY REF_O;